jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:

        site:
            pattern:    ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
            logout:             true
            anonymous:          true

#        admin:
#            pattern:    ^/admin
#            form_login:
#                provider:       fos_userbundle
#                csrf_provider:  form.csrf_provider
#            logout:             true
#            anonymous:          true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

